FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY build/libs/cinema-recommendation-0.0.1-SNAPSHOT.jar /app/cinema-recommendation.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/cinema-recommendation.jar"]
